// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yapavwgoguwwgijxijai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhcGF2d2dvZ3V3d2dpanhpamFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODI5NDAsImV4cCI6MjA2NTk1ODk0MH0.hRug7Ov6WbniWLCkwRP6fZ9NgPK7bkjawoRe6agfvv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);